apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ivy-deployment-example
spec:
  name: ivy-mnist-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: ivy_model:0.1
          name: mnist-classifier
          imagePullPolicy: Never
          env:
          # https://docs.seldon.io/projects/seldon-core/en/latest/python/python_server.html#disable-multithreading
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: GRPC_WORKERS
            value: '0'
          - name: SELDON_DEBUG
            value: '1'
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: mnist-classifier
      type: MODEL
    labels:
      version: v1
    name: example
    replicas: 1